### ISSUE TITLE
APT source whitelist request for ppa:duggan/bats

### ISSUE THREAD

**Issue by mxplusb** [travis-ci/apt-source-whitelist#167] opened 2015-10-05 23:22 UTC
`ppa:duggan/bats` is nice for Bash testing. Needed for testing CLI applications in a Bash shell

**Comment by danpoltawski** [comment] 2016-07-12 17:22
This is a dupe of #108

**Comment by jayvdb** [comment] 2017-02-17 01:35
@mxplusb ping; can you close this dup?

**Closed** 2017-02-17 04:54 UTC
