### ISSUE TITLE
PPA for PHP 5.6

### ISSUE THREAD

**Issue by p-h-p** [travis-ci/apt-source-whitelist#209] opened 2015-12-15 14:39 UTC
`apt` repository is `ppa:ondrej/php5-5.6` by [Ondřej Surý](https://launchpad.net/~ondrej/+archive/ubuntu/php5-5.6)

**Comment by austerus** [comment] 2015-12-23 09:58
Duplicate of https://github.com/travis-ci/apt-source-whitelist/issues/70 ?

**Closed** 2017-08-28 17:57 UTC
